image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init done'
    command: |
      clear
      ipfs init --profile server
      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*", "http://localhost:3000", "http://127.0.0.1:5001", "https://webui.ipfs.io"]
      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "POST"]'
      ipfs daemon
